service: blog

provider:
  name: google
  runtime: nodejs
  project: serverless-170909
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - blogs/**
    - '!blogs/public/**'

functions:
  blog:
    handler: blog
    events:
      - http: path
